### ISSUE TITLE
Need for a contribution guide.

### ISSUE THREAD

**Issue by mtendekuyokwa** [JoelFickson/pawapay_api#2]
Hello,
 I would love to write up a contrubution guide for people who would love to contribute to the project. The contribution guide would have a short description of what the project is and what problem it solves.
I know how to write markdown but I have never had experience writing node and rust. I have written vanilla js though.

**Comment by joelfickson** [comment]
Please go ahead and write it.

**Comment by mtendekuyokwa** [comment]
Thank you. I have written it and created a pull request
